services:
  ollama:
    runtime: amd
    restart: always
    container_name: ollama
    image: ollama/ollama:rocm  # Replace with specific Ollama version if needed
    environment:
      HSA_OVERRIDE_GFX_VERSION: 10.3.0
    deploy:
      resources:
        reservations:
          devices:
          - driver: amd
            capabilities: ["gpu"]
            count: all  # Adjust count for the number of GPUs you want to use
    volumes:
      - ollama:/root/.ollama
    networks:
      - default
    ports:
      - 11444:11434

  openwebui:
    restart: always
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    volumes:
      - open-webui:/app/backend/data
    networks:
      - default
    ports:
      - 4444:8080

volumes:
  ollama:
  open-webui:

networks:
  default: